---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: I privilegi minimi di ONTAP richiesti variano in base ai plug-in di SnapCenter utilizzati per la protezione dei dati. 
---
= Privilegi ONTAP richiesti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I privilegi minimi di ONTAP richiesti variano in base ai plug-in di SnapCenter utilizzati per la protezione dei dati.



== Sono richiesti privilegi minimi per ONTAP

Tutti i plug-in di SnapCenter richiedono i seguenti privilegi minimi.

|===
| All-access comands (comandi all-access): Privilegi minimi richiesti per ONTAP 8.3 e versioni successive 


| event generate-autosupport-log 


| mostra la cronologia dei lavori
interruzione del lavoro 


| lun
lun create (crea lun)
lun delete (elimina lun)
lun igroup add
lun igroup create
lun igroup delete (elimina igroup lun)
lun igroup rename (rinomina lun igroup)
lun igroup show
lun mapping add-reporting-node
creazione mappatura lun
eliminazione della mappatura lun
nodi di remove-reporting-mapping lun
visualizzazione della mappatura del lun
modifica del lun
lun move-in-volume
lun offline
lun online
lun persistent-reservation clear
ridimensionamento del lun
lun seriale
lun show 


| elenco-destinazioni snapmirror
regola aggiuntiva del criterio snapmirror
regola-modifica del criterio snapmirror
regola di rimozione del criterio snapmirror
policy di snapmirror
ripristino di snapmirror
spettacolo di snapmirror
storia di snapmirror
aggiornamento di snapmirror
snapmirror update-ls-set 


| Versione 


| creazione del clone del volume
visualizzazione del clone del volume
avvio della divisione del clone del volume
interruzione della divisione del clone del volume
creazione del volume
distruggere il volume
creazione del clone del file di volume
file di volume show-disk-usage
volume offline
volume online
modifica del volume
creazione del qtree del volume
eliminazione del qtree del volume
modifica del qtree del volume
visualizzazione del qtree del volume
limitazione del volume
presentazione del volume
creazione di snapshot di volume
eliminazione dello snapshot del volume
modifica dello snapshot del volume
rinominare lo snapshot del volume
ripristino dello snapshot del volume
file di ripristino dello snapshot del volume
visualizzazione di snapshot di volume
smontare il volume 


| cifs vserver
creazione condivisione cifs vserver
eliminazione condivisione cifs vserver
vserver cifs shadowcopy mostra
show di condivisione di vserver cifs
vserver cifs show
policy di esportazione di vserver
creazione policy di esportazione vserver
eliminazione della policy di esportazione di vserver
creazione della regola dei criteri di esportazione di vserver
visualizzazione della regola dei criteri di esportazione di vserver
visualizzazione della policy di esportazione di vserver
iscsi vserver
visualizzazione della connessione iscsi del vserver
show di vserver
interfaccia di rete
gruppi di failover dell'interfaccia di rete
visualizzazione dell'interfaccia di rete 
|===
|===
| Comandi di sola lettura: Privilegi minimi richiesti per ONTAP 8.3 e versioni successive 


| server virtuale
peer vserver 
|===

NOTE: È possibile ignorare i messaggi di avviso relativi ai comandi vserver non supportati.



== Ulteriori informazioni su ONTAP

* Se si utilizza ONTAP 8.2.x:
+
Devi effettuare l'accesso come `vsadmin` Sulla VM di storage per disporre dei privilegi appropriati per il plug-in SnapCenter per le operazioni di VMware vSphere.

* Se si utilizza ONTAP 8.3 e versioni successive:
+
Devi effettuare l'accesso come `vsadmin` o con un ruolo che ha i privilegi minimi elencati nelle tabelle precedenti.

* Per creare e gestire i ruoli utente, è necessario essere l'amministratore del cluster. È possibile associare gli utenti a una macchina virtuale per lo storage in cluster o a una macchina virtuale per lo storage.

